hyperledger/fabric-sdk-node

fabric-client/lib/Client.js, fabric-client/lib/Package.js, fabric-client/test/Client.js
Signed-off-by: bharadwajambati1 <bharadwaj.ambati1@ibm.com>
Change-Id: Iad9f15823b12b50787aa3d7ef8dd292043ffb321
=> [FABN-1393] Pass baseDir/gopath from client to node-sdk

.gitignore, azure-pipelines.yml, fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, fabric-client/test/data/java-contract/build.gradle, fabric-client/test/data/javaWithFabricIgnores-contract/build.gradle, fabric-common/package-lock.json, fabric-common/package.json, fabric-network/package-lock.json, package-lock.json, package.json
- Update x509 dependency version (current version causing tests to fail)
- Pulled in @bestbeforetoday 's commit to fix docker issues
- Re-arranged jitpack links so java chaincode contracts try it last in the build.gradle files
- Updated gitignore to ignore java contract build files
- Added package-lock.jsons
- Removed some references to gerrit mirror
=> [FABN-1418] Fix builds and add package-locks

fabric-network/types/index.d.ts
Fixes the HSMWalletMixin constructor defiition
Signed-off-by: Liam Grace <liam.grace@ibm.com>
=> FABN-1419: Fix HSMWalletMixin typescript definition

.editorconfig, azure-pipelines.yml, scripts/ci_scripts/azurePublishApiDocs.sh, scripts/ci_scripts/azurePublishNpmPackages.sh, test/fixtures/src/java_cc/example_cc/build.gradle, test/fixtures/src/java_cc/example_cc1/build.gradle
=> FABN-1386: Publish docs to gh-pages branch

fabric-client/types/index.d.ts
Add typings for a private data collection configuration
and endorsmeent policy to ChaincodeInstantiateUpgradeRequest.
Change-Id: I32f1789dbb96fecc88d03fcd841356d21fcb89e9
=> [FABN-1407] Add PDC and EP types (1.4)

azure-pipelines.yml
=> FABN-1386: Reference credentials in pipeline script

azure-pipelines.yml, scripts/ci_scripts/azurePublishApiDocs.sh
- Git and find usage tweaked for cross-platform compatibility
- Ensure publishing script fails fast on any errors
- Add some additional information output
=> FABN-1386: Doc publishing fixes

scripts/ci_scripts/azurePublishNpmPackages.sh
=> FABN-1386: Tidy up npm publish script

.gitignore, fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, fabric-common/package-lock.json, fabric-network/package-lock.json, fabric-network/package.json, fabric-protos/package.json, package-lock.json
- mostly package-lock.jsons needed for auditing
=> Port relevant changes from PR#33

fabric-client/types/index.d.ts
Add typings for a private data collection configuration
and endorsmeent policy to ChaincodeInstantiateUpgradeRequest.
Change-Id: I32f1789dbb96fecc88d03fcd841356d21fcb89e9
=> [FABN-1407] Add PDC and EP types (2.0)

fabric-network/src/impl/event/abstracteventlistener.js, fabric-network/test/impl/event/abstracteventlistener.js
Signed-off-by: Liam Grace <liam.grace@ibm.com>
=> [FABN-1307] Pass options.unregister through to clientOptions.unregister

fabric-client/lib/Channel.js, fabric-client/lib/utils.js
Modify pem encoded certificates if including multiple
certificates and not separated by a new line
=> FABN-1403 NodeSDK modify multicert pems

build/tasks/test.js, fabric-common/lib/Channel.js, fabric-common/lib/Client.js, fabric-common/lib/Commit.js, fabric-common/lib/Discoverer.js, fabric-common/lib/DiscoveryService.js, fabric-common/lib/Endorsement.js, fabric-common/lib/Endorser.js, fabric-common/lib/EventListener.js, fabric-common/lib/EventService.js, fabric-common/lib/Proposal.js, fabric-common/lib/Query.js, fabric-common/lib/ServiceAction.js, fabric-common/lib/ServiceEndpoint.js, fabric-common/lib/ServiceHandler.js, fabric-common/test/BaseClient.js, fabric-common/test/Channel.js, fabric-common/test/Commit.js, fabric-common/test/DiscoveryService.js, fabric-common/test/Endorsement.js, fabric-common/test/EventListener.js, fabric-common/test/EventService.js, fabric-common/test/Proposal.js, fabric-common/test/Query.js, fabric-common/test/ServiceEndpoint.js, fabric-common/test/User.js, test/scenario/features/steps/base_steps.js
Update fabric-common with changes to help with
the integration with the high level SDK
=> FABN-1347 NodeSDK update low level

azure-pipelines.yml
Adds the NPM credentials group
Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>
=> Add NPM Creds to CI

fabric-network/index.js, fabric-network/src/impl/wallet/couchdbwalletstore.ts, fabric-network/src/impl/wallet/filesystemwalletstore.ts, fabric-network/src/impl/wallet/inmemorywalletstore.ts, fabric-network/src/impl/wallet/wallet.ts, fabric-network/src/impl/wallet/wallets.ts, fabric-network/src/impl/wallet/walletstore.ts, fabric-network/test/impl/wallet/wallet.spec.ts, fabric-network/test/impl/wallet/walletstore.spec.ts
=> Align Java and Node wallet API naming

fabric-ca-client/package.json, fabric-client/README.md, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, fabric-protos/package.json, package.json, release_notes/v2.0.0-beta.txt
Updates to publish the v2.0.0 beta
=> FABN-1432 NodeSDK publish v2 beta.1

fabric-network/src/impl/event/abstracteventlistener.js, fabric-network/test/impl/event/abstracteventlistener.js
https://jira.hyperledger.org/browse/FABN-1308
Signed-off-by: Liam Grace <liam.grace@ibm.com>
=> [FABN-1308] Enable checkpointing when start or end block are given

fabric-network/lib/impl/event/abstracteventlistener.js, fabric-network/test/impl/event/abstracteventlistener.js
https://jira.hyperledger.org/browse/FABN-1308
Signed-off-by: Liam Grace <liam.grace@ibm.com>
=> [FABN-1308] Enable checkpointing when start or  end block is given

fabric-client/lib/packager/Lifecycle.js, fabric-client/package-lock.json, fabric-network/package-lock.json, fabric-network/package.json, package-lock.json, package.json
=> [FABN-1435] Remove stream-buffers from lifecycle code

scripts/npm_scripts/generateCerts.js
While trying to update links, wrapping your head around what is happening in this file is tough due to all the concatenation, using interpolation makes is trivial to read
Signed-off-by: Brett Logan <you@example.com>
=> Improve readability by using interpolation

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, fabric-protos/package.json, package.json
This reverts commit 5124fd7876fffb6b5c055daefd5fa0697723a4b3.
=> Revert "[FABN-1435] Publish 2.0.0-beta.2"

azure-pipelines.yml, fabric-ca-client/test/FabricCAServices.js, fabric-client/test/Policy.js, package-lock.json
=> FABN-1439: Use Node 12

README.md, fabric-ca-client/README.md, fabric-client/README.md, fabric-client/lib/Channel.js, fabric-common/README.md, fabric-network/README.md, fabric-protos/README.md, release_notes/v1.4.0.txt, release_notes/v2.0.0-alpha.txt, release_notes/v2.0.0-beta.txt
=> FABN-1428: Point to new API documentation site

CODEOWNERS, MAINTAINERS.rst
=> (Master) Add Mark Lewis as a maintainer

MAINTAINERS.rst
=> (Release-1.4) Add Mark Lewis as a maintainer

MAINTAINERS.rst
=> Add Heather Pollard as maintainer

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json, release_notes/v1.4.5.txt
Update package.json to publish 1.4.5
=> FABN-1450 NodeSDK publish 1.4.5

fabric-client/test/data/java-contract/build.gradle, fabric-client/test/data/javaWithFabricIgnores-contract/build.gradle
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
=> Update Nexus URLs to Artifactory

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json
Update the package.jsons to allow for fixes and development
of the 1.4.6 of release-1.4 branch.
=> FABN-1460 NodeSDK set release 1.4 snapshot

.eslintignore, .eslintrc.json, fabric-client/.eslintignore, fabric-client/lib/Policy.js, fabric-client/lib/impl/DiscoveryEndorsementHandler.js, fabric-client/types/tsconfig.json, fabric-common/.eslintignore, fabric-network/lib/contract.js, fabric-network/lib/impl/event/abstracteventlistener.js, fabric-network/lib/impl/event/filesystemcheckpointer.js, fabric-network/lib/network.js, fabric-network/test/network.js, package.json, test/integration/channel-event-hub.js, test/integration/e2e/e2eUtils.js, test/integration/e2e/join-channel.js, test/integration/get-config.js, test/integration/install.js, test/integration/instantiate.js, test/integration/invoke.js, test/integration/only-admin.js, test/integration/upgrade.js, test/scenario/features/lib/channel.js
From master, commit hash is 67365b5ea7a5319f26c59e500b2420b61af95dc4
=> [FABN-1039] Cherry pick of changes delivered under "Create eslint task"

README.md, docs/redirectTemplates/404.html, fabric-ca-client/README.md, fabric-client/README.md, fabric-client/lib/Channel.js, fabric-common/README.md, fabric-network/README.md
=> Fix some broken docs links

fabric-network/lib/transaction.js
Add jsdoc for peer responses in exception
Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>
=> FABN-1451 add peer responses to error

README.md, azure-pipelines.yml, fabric-ca-client/lib/FabricCAServices.js, fabric-ca-client/package.json, fabric-ca-client/test/FabricCAServices.js, fabric-client/package.json, fabric-client/test/Policy.js, fabric-common/package.json, fabric-network/package.json, test/unit/channel.js
- Run node 10 and 12 sequentially
- Fix some strings in the tests
- Update package package.jsons
- Fixed typos
=> [FABN-1481] Remove node 8 support and add node 12

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package-lock.json, package.json, release_notes/v1.4.6.txt
=> [FABN-1487] Release 1.4.6

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/.npmignore, fabric-network/package.json, package-lock.json, package.json
- Also added .npmignore file to fabric-network, which currently publishes test files
=> [FABN-1487] Revert release-1.4 branch to release snapshots

azure-pipelines.yml
=> [FABN-1500] Fix fabric-ca-client builds

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package-lock.json, package.json, release_notes/v1.4.7.txt
=> Release v1.4.7

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package-lock.json, package.json
- Also upped the version of fabric we test with to 1.4.6, released yesterday
=> Revert to releasing snapshots after 1.4.7

fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, fabric-common/package-lock.json, fabric-common/package.json, fabric-network/package-lock.json, fabric-network/package.json, package-lock.json, package.json
=> [FABN-1505] List winston as dependency for all packages

fabric-network/lib/network.js, fabric-network/lib/transaction.js, fabric-network/test/network.js, fabric-network/test/transaction.js, fabric-network/types/index.d.ts, test/typescript/integration/network-e2e/invoke.ts
Signed-off-by: Dave K <d_kelsey@uk.ibm.com>
add setEndorsingOrganizations support
=> FABN-1508 setEndorsingOrganizations support

CHANGELOG.md, fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, fabric-common/package-lock.json, fabric-common/package.json, fabric-network/package-lock.json, fabric-network/package.json, package-lock.json, package.json, release_notes/v1.4.8.txt
=> FABN-1517 Publish 1.4.8

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json
=> FABN-1517 Fix release-1.4 tags for 1.4.8 release

fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, fabric-client/test/ChannelEventHub.js, fabric-common/package-lock.json, fabric-common/package.json, fabric-network/package-lock.json, fabric-network/package.json, package-lock.json, package.json
=> FABN-1517 Revert to 1.4.9-snapshots

fabric-client/lib/Orderer.js
align with Peer.js
Signed-off-by: davidliu <david-khala@hotmail.com>
=> [FABN-1538] provide similar _createClients in orderer.js

fabric-ca-client/lib/helper.js, fabric-ca-client/package-lock.json, fabric-ca-client/package.json, fabric-client/package-lock.json, fabric-client/package.json, package-lock.json, package.json, test/unit/ecdsa-key.js
move from v7 to v8 of jsrsasign
=> FABN-1568 release-1.4 upgrade jsrsasign

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json, release_notes/v1.4.9.txt
=> FABN-1575 Publish NodeSDK 1.4.9

fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json
set the version to 1.4.10-snaphot
set the tag to unstable-1.4
=> FABN-1577 return release-1.4 to snapshot

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json, release_notes/v1.4.10.txt
Publish new version of release-1.4
=> FABN-1589 Publish 1.4.10

test/fixtures/docker-compose/.env
=> FABN-1600: Add license to .env file

fabric-client/lib/Channel.js, fabric-client/test/Channel.js
Allow users to get the capabilities of the their channel
=> FABN-1621 Add capability decode

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json, release_notes/v1.4.12.txt
=> FABN-1628 publish release 1.4.12

CHANGELOG.md, fabric-ca-client/package.json, fabric-client/package.json, fabric-common/package.json, fabric-network/package.json, package.json, release_notes/v1.4.13.txt
Update all package.json for release-1.4 at 1.4.13
=> FABN-1636 Publish 1.4.13

fabric-client/package.json, package-lock.json, package.json
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>
=> [FABN-1623]-Update elliptic dependency

fabric-client/package-lock.json, package-lock.json
Signed-off-by: lesleyannj <lesleyannj@hotmail.com>
=> [FABN-1626] Update dependencies
