- .editorconfig
- build/tasks/doc.js
- scripts/ci_scripts/azurePublishApiDocs.sh
Invoke documentation generation with the correct branch name so
that built documentation is published under the correct
sub-directory for the current branch. Previously, all branches
published their documentation as master.
> FABN-1386: Publish correct doc release directory

- test/ts-scenario/steps/channel_operations.ts
- test/ts-scenario/steps/cli.ts
- test/ts-scenario/steps/deprecated.ts
- test/ts-scenario/steps/lib/chaincode.ts
- test/ts-scenario/steps/lib/channel.ts
- test/ts-scenario/steps/lib/contract.ts
- test/ts-scenario/steps/lib/deprecatedSDK.ts
- test/ts-scenario/steps/lib/gateway.ts
- test/ts-scenario/steps/lib/listeners.ts
- test/ts-scenario/steps/lib/utility/adminUtils.ts
- test/ts-scenario/steps/lib/utility/baseUtils.ts
- test/ts-scenario/steps/lib/utility/clientUtils.ts
- test/ts-scenario/steps/network-model.ts
- tslint.json
Concurrency issue in the tests where they did not wait for peers to
commit lifecycle operations, which they would later use to query
status of those lifecycle operations.
Changed test code to wait for commit events from all network peers
before proceeding when performing lifecycle operations.
> FABN-1424: Fix lifecycle scenario tests

- fabric-client/lib/packager/BufferStream.js
- fabric-client/lib/packager/Golang.js
- fabric-client/lib/packager/Java.js
- fabric-client/lib/packager/Node.js
- fabric-client/package.json
- fabric-client/test/packager/BufferStream.js
- fabric-client/test/packager/Golang.js
- fabric-client/test/packager/Java.js
- fabric-client/test/packager/Node.js
- package.json
Use custom writable stream implementation instead
of inefficient stream-buffers package when building
smart contract packages.
Change-Id: I51de2aa6cc62933340dd31e6b3af36f376c6f646
> [FABN-1342] Improve SDK packaging performance

- azure-pipelines.yml
npm credentials must be imported to allow publishing to npm as part
of the merge builds.
> FABN-1386: Import npm credentials in build

- fabric-ca-client/package.json
- fabric-client/package.json
- fabric-common/package.json
- fabric-network/package.json
- fabric-protos/package.json
- package.json
return version and tag to snapshot and unstable in the
package.jsons to be able to continue development
> FABN-1433 NodeSDK return to snapshot

- docs/jsdoc.json
- scripts/ci_scripts/azurePublishApiDocs.sh
> FABN-1039: Fix master branch doc publishing

- fabric-client/lib/utils.js
In the case where a certificate chain is not separated by
a new line, one will be added.
> FABN-1403 NodeSDK add new line to certs

- fabric-client/lib/Orderer.js
- fabric-client/lib/Peer.js
- fabric-client/lib/Remote.js
- fabric-client/test/Orderer.js
- fabric-client/test/Peer.js
- test/unit/channel.js
- test/unit/commit-handler.js
- test/unit/remote.js
The gRPC setup 'waitForReady' on services is an optional setup
step on a service connection that could be bypassed when not
required by the application.
Allow for a connection option to skip and move straight to
sending the outbound request.
> FABN-1463 NodeSDK make waitForReady optional

- fabric-network/lib/transaction.js
- fabric-network/test/transaction.js
- test/typescript/integration/network-e2e/invoke.ts
In submitTransaction(), if there are no valid responses from peers, an error is thrown back to the client.
This PR adds the array of responses to the error object.
Signed-off-by: andrew-coleman <andrew_coleman@uk.ibm.com>
> FABN-1451 add peer responses to error

- fabric-ca-client/types/index.d.ts
JIRA: https://jira.hyperledger.org/browse/FABN-1430
The names of the members of IServiceResponse should start with small
letters as per lib/serverendpoint.go in fabric-ca.
Signed-off-by: Taku Shimosawa <taku.shimosawa@hal.hitachi.com>
> [FABN-1430] Fix type for IServiceResponse

- fabric-ca-client/types/index.d.ts
The name of the members of IServiceResponse should start with small
letters as per lib/serverendpoint.go in fabric-ca.
Signed-off-by: Taku Shimosawa <taku.shimosawa@hal.hitachi.com>
> [FABN-1430] Fix type for IServiceResponse (#62)

- docs/index.md
Also remove Node 8 since it out of support and we do not test with it.
> FABN-1481: Add Node 12 to compatibility matrix

- fabric-client/lib/utils.js
function calls to CKS were assuming they returned promises. however the default implementation is a synchronous call. I have updated the code to leverage async/await which will handle both the cases where CKS is meant to be sync or async.
> FABN-1515: consume CKS as a synchronus function

- fabric-client/lib/ChannelEventHub.js
Fix timeout error that occurs when we immediately
reconnect EventHub. The cause of this problem is
inappropreate handling of incomming reset message
for the disconnected stream.
Change-Id: Ifa9802b7c5e71124ea6ec3ed3c4afd73102bce26
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>
(cherry picked from commit 60d160dbdf098acd99ec3d3f636fd4987fe2ee60)
> FABN-1512: Port changes from FABN-1257 to 1.4 stream

- fabric-client/types/index.d.ts
When excluding `node_modules` in tsconfig.json typescript will throw errors when building a project 
using the fabric client.
```
node_modules/fabric-client/types/index.d.ts:635:21 - error TS2304: Cannot find name 'ByteBuffer'.
635  	signature_header: ByteBuffer;
node_modules/fabric-client/types/index.d.ts:711:18 - error TS2304: Cannot find name 'Long'.
711  	ledger_height: Long;
```
I found references to other users experiencing the same problem in the Hyperledger JIRA:
https://jira.hyperledger.org/browse/FAB-5581
> Import ByteBuffer and Long types to prevent TypeScript errors

- docs/tutorials/query-peers.md
- docs/tutorials/transaction-commit-events.md
Broken links to sample code in the tutorial pages for query handlers and transaction handlers.
> FABN-1556: Fix broken doc links

- fabric-network/lib/errors/transactionerror.js
- fabric-network/lib/impl/event/transactioneventhandler.js
- fabric-network/test/errors.js
- fabric-network/test/impl/event/transactioneventhandler.js
- fabric-network/types/index.d.ts
Users will be able to check the transaction code when their
error callback is called with an error. The error will be of
type 'TransactionError' and it will have an attribute of
'transactionCode' along with the 'transactionId'.
> FABN-1566 add transaction code to event error

- fabric-client/lib/Client.js
- fabric-client/test/Client.js
Use tlsCACerts as defined in the common connection profile
to avoid wrapping an array in an array. Both a single string
and an array of strings are valid for connecting to a Fabric-CA.
> FABN-1586 Do not wrap tlsCACerts

- fabric-client/lib/Client.js
- fabric-client/test/Client.js
When the fabric-client.Client builds a FabricCAService
instance for the user from the information of a common
connection profile it should use false as the tls verify
option when one is not defined.
> FABN-1587 Use false as the default verify option

- fabric-ca-client/package.json
- fabric-client/package.json
- fabric-common/package.json
- fabric-network/package.json
- package.json
- scripts/ci_scripts/azurePublishNpmPackages.sh
Cherry-pick of 6f29724ed68a20fa10a00f3c17a617a02a55e3f5
Rather than increment the snapshot version of whichever version was last published for a given tag, use the next available snapshot version for the given release version.
Also update versions and npm tags to snapshot/unstable following release.
> FABN-1600: Better unstable version generation (#248)

- fabric-client/types/index.d.ts
Add the Channel.getChannelCapabilities() def to the typescript index.
> FABN-1621 Add typescript defs for getChannelCapabilities

- fabric-client/lib/Channel.js
- fabric-client/test/Channel.js
The method must handle cases where configs do not have the
Capabilities and throw an error if the input is not a valid
config envelope.
> FABN-1621 getChannelCapabilities handle only valid envelope

- fabric-client/lib/Channel.js
- fabric-client/lib/Orderer.js
- fabric-client/lib/impl/BasicCommitHandler.js
- test/unit/commit-handler.js
Randomize the discovered orderer list for load balance.
Have the discovery commit handler skip orderers that are not
on-line to avoid delays in using non responding orderers.
Orderers will attempt a reconnect on the discovery refresh cycle.
> FABN-1632 Enhance discovery orderer failover

- scripts/ci_scripts/azurePublishNpmPackages.sh
v2 packages are tagged as latest so all v1.4 packages are now tagged as latest-1.4. However, there is no v2 fabric-client so the latest tag has been orphaned. To avoid this, explicitly tag stable releases of fabric-client as latest.
> FABN-1649: Tag stable releases of fabric-client as latest
